filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log

strict.perms: false

processors:
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"
