{
 "title": "CI/CD Demo App",
 "panels": [
  {
   "title": "HTTP Requests / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Uptime (seconds)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "process_uptime_seconds" }
   ]
  },
  {
   "title": "Memory RSS (bytes)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "process_resident_memory_bytes" }
   ]
  }
 ]
}