pipeline {
  agent any

  environment {
    VAULT_ADDR = "http://vault:8200"
  }

  stages {
    stage('Lint') {
      steps {
        sh 'make lint'
      }
    }
    stage('Test') {
      steps {
        sh 'make test'
      }
    }
    stage('Drift Check') {
      steps {
        sh './scripts/drift-check.sh dev || true'
      }
    }
  }

  post {
    always {
      archiveArtifacts artifacts: 'terraform/**/*.tf', fingerprint: false
    }
  }
}
