name: rotate-secrets

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  rotate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rotate secret in Vault
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        run: |
          docker run --rm \
            -e VAULT_ADDR \
            -e VAULT_TOKEN \
            -v "${{ github.workspace }}/Secure Secrets Management & Observability Toolkit/vault/init/rotate-secret.sh:/rotate-secret.sh:ro" \
            hashicorp/vault:1.15.6 /bin/sh /rotate-secret.sh
