name: supply-chain-pipeline

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build_scan_sign:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/devsecops-demo:${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        run: |
          docker build -t "$IMAGE_NAME" app
          docker push "$IMAGE_NAME"

      - name: Generate SBOM (Trivy)
        run: |
          mkdir -p artifacts
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$PWD/artifacts:/artifacts" aquasec/trivy:latest image --quiet \
            --format cyclonedx --output /artifacts/sbom.cdx.json "$IMAGE_NAME"

      - name: Scan dependencies (Trivy)
        run: |
          docker run --rm -v "$PWD/app:/workspace" aquasec/trivy:latest fs --quiet \
            --scanners vuln --exit-code 1 --severity HIGH,CRITICAL /workspace

      - name: Scan dependencies (Grype)
        run: |
          docker run --rm -v "$PWD/app:/workspace" anchore/grype:latest \
            dir:/workspace --fail-on high -q

      - name: Scan image (Trivy)
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image --quiet --exit-code 1 --severity HIGH,CRITICAL "$IMAGE_NAME"

      - name: Scan image (Grype)
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            anchore/grype:latest "$IMAGE_NAME" --fail-on high -q

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0

      - name: Sign image
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          if [ -n "$COSIGN_PRIVATE_KEY" ]; then
            echo "$COSIGN_PRIVATE_KEY" > cosign.key
            cosign sign --yes --key cosign.key "$IMAGE_NAME"
          else
            cosign sign --yes "$IMAGE_NAME"
          fi

      - name: Attest provenance
        run: |
          cosign attest --yes --predicate policy/provenance.json \
            --type https://slsa.dev/provenance/v0.2 "$IMAGE_NAME"

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: artifacts/sbom.cdx.json
