{
 "title": "Ecommerce Services",
 "tags": [
  "ecommerce",
  "spring-boot"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Order Service Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"order-service\"}"
    }
   ]
  },
  {
   "title": "Inventory Service Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"inventory-service\"}"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (application) (rate(http_server_requests_seconds_count[1m]))"
    }
   ]
  }
 ]
}