pipeline {
  agent any

  stages {
    stage('Lint') {
      steps {
        sh 'make lint'
      }
    }
    stage('Test') {
      steps {
        sh 'make test'
      }
    }
    stage('Build') {
      steps {
        sh 'make build'
      }
    }
  }

  post {
    always {
      cleanWs()
    }
  }
}
